### PR TITLE
Add TCA9554 peripheral power control for neopixel support

### PR DESCRIPTION
**Pull request by skieast**
Added support for onboard neopixel that has its power control via the TCA9554

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
thank you for your PR, I don't have this board to test with, but it looks good. `IR_RGB_CTRL` is connected to P6 of TCA9554. Though i have a question during the boot2 stage, it will try to turn on the neopixel purple to indicate double reset, would that work as well (I guess not).

image

**Comment by skieast** [comment]
True, the PERI_POWER is not enabled during boot2.  I may look at that but am more interested in getting the display working. My test board display has actually stopped working so NEOPIXEL came to the front. Thanks for looking at this.

**Comment by hathach** [comment]
> True, the PERI_POWER is not enabled during boot2. I may look at that but am more interested in getting the display working. My test board display has actually stopped working so NEOPIXEL came to the front. Thanks for looking at this.

thank for confirmation with boot2, this is still good to merge.

**Review by hathach — APPROVED** [review]
thank you for your PR, look good

**Pull request merged**
