### PR TITLE
Add s3 support

### PR DESCRIPTION
**Pull request by hathach**
- add board.cmake to explicitly set IDF_TARGET (to s2 or s3)
- add s3 devkit c and devkit m
- update tinyusb
  - fix net_device.c file changes
  - rename dcd_transdimension to chipidea
  - st synopsys to dwc2

### CODE REVIEW

**Comment by UnexpectedMaker** [comment]
Oh that's crazy - I was working on trying to get S3 going on Tuesday, and got close, but was not able to get past the last few compile errors... and then today I see this!

Gonna give it a whirl now!

**Comment by hathach** [comment]
> Oh that's crazy - I was working on trying to get S3 going on Tuesday, and got close, but was not able to get past the last few compile errors... and then today I see this!
> 
> Gonna give it a whirl now!

Let me know if you spot any issue

**Comment by UnexpectedMaker** [comment]
> > Oh that's crazy - I was working on trying to get S3 going on Tuesday, and got close, but was not able to get past the last few compile errors... and then today I see this!
> > Gonna give it a whirl now!
> 
> Let me know if you spot any issue

It's actually working great! I have created folders for my 3 new ESP32-S3 boards, and built all of them and they boot perfectly - except I've not been able to build CircuitPython for the S3, so I don't have anything to copy onto them to check that - yet ;)

Thanks for getting this working. I can see from your PR what things I missed when I tried. Not sure I'd ever have found them all :)

**Comment by hathach** [comment]
you could use the uf2 for s3 devkitc to test with https://github.com/adafruit/circuitpython/tree/main/ports/espressif/boards/espressif_esp32s3_devkitc_1 . I have tested it before switching the uf2 family for S3 to new ID. For now, you need to wait for the https://github.com/adafruit/circuitpython/pull/5771 to update the family id.

**Pull request merged**
