### PR TITLE
Ghostfat test boards

### PR DESCRIPTION
**Pull request by henrygab**
The goal of this branch is to enable, as part of the normal build process, validation of GhostFat image generation.

* [x] Create framework to execute own custom `test_main()` function, using existing code
* [x] Ensure ghostfat initialization completes prior to calling `test_main()`
* [x] Generate disk image file from `test_main()`
* [x] Validate bit-for-bit accuracy of disk image file from `test_main()`
* [x] Use common framework code for variations of desired file system image
* [x] Check in known-good file system image(s) to validate against
* [x] Double-compress known-good disk images
* [x] Ensure CI catches failures

NOTE: When the ghostfat image that is generated *would* need to change, such as for a bugfix, then updated versions of the known-good file system images would also need to also be committed.

### CODE REVIEW

**Comment by henrygab** [comment]
@hathach -- Can you help with two things?

1. Getting this to compile in the CI builds
2. Getting the compiled , and ensuring CI will execute the resulting binary.

#### Compilation:
On my Ubuntu system, to make the test ports compile requires removing two options from `make.mk` and `rules.mk`:

https://github.com/adafruit/tinyuf2/blob/54cff8b6a2c84f2ea944d5df27fd5099763d3674/ports/make.mk#L136-L137

https://github.com/adafruit/tinyuf2/blob/54cff8b6a2c84f2ea944d5df27fd5099763d3674/ports/rules.mk#L12

**Comment by hathach** [comment]
> Collapsing to reduce thread length
> @hathach -- Can you help with two things?
> 
> 1. Getting this to compile in the CI builds
> 2. Getting the compiled , and ensuring CI will execute the resulting binary.
> 
> #### Compilation:
> On my Ubuntu system, to make the test ports compile requires removing two options from `make.mk` and `rules.mk`:
> 
> https://github.com/adafruit/tinyuf2/blob/54cff8b6a2c84f2ea944d5df27fd5099763d3674/ports/make.mk#L136-L137
> 
> https://github.com/adafruit/tinyuf2/blob/54cff8b6a2c84f2ea944d5df27fd5099763d3674/ports/rules.mk#L12

no problems at all, leave that to me. I just resolved the conflict with master and push the update. Give me a bit of time to go through the code. I think I could setup unit tests with CMock/Unity using your tests. That would be easier to run on ci and a bit cleaner look for the ports. Will post more update.

**Comment by henrygab** [comment]
@hathach -- Yes, it was a few days back.  Since then, I got it to work with CI.

So, you can do nothing, and it will validate the file system generation continues to work.

**Comment by henrygab** [comment]
OK, this is ready for review.  See success in checks from commit [deae8ca](https://github.com/adafruit/tinyuf2/pull/94/checks?sha=deae8cab076fdf47982208122e819e9fe8759568) ... listing the four GhostFAT code compiling, comparing against known-good images, and even ignoring the two very narrow exceptions required.

<details><summary>Two exceptions detailed</summary><P/>

Two variations allowed from the known good file system:
1. Contents of `UF2_INFO.TXT` file will have a variable-length string in the middle that differs for each commit.
2. The directory entry for `UF2_INFO.TXT` may indicate a different file size.

The code allows very narrow exceptions with multiple checks, to allow these two differences, without allowing other regressions to fall through.
</details>

**Review by hathach — APPROVED** [review]
Brilliant !! Thank you very much for your effort and time put into this PR. Though I still think we should separate the native build from current build system for unit test cmock/unity. I will merge this now and make a follow up PR to decouple the native build. Thank you very much for your awesome work !!!!

**Comment by henrygab** [comment]
Sorry, please ignore this "review request" ... accidental click.

**Comment by hathach** [comment]
no problem at all :)

**Pull request merged**
