### PR TITLE
Added my new TinyS3, FeatherS3 and ProS3 boards

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
All PIDs are from Espressif.

### CODE REVIEW

**Comment by ladyada** [comment]
thach will return after Tet!

**Comment by UnexpectedMaker** [comment]
> thach will return after Tet!

Yup, that's cool :)
I just wanted to get this in as it's been sitting in my repo for a few weeks and I didn't want to forget!

**Comment by hathach** [comment]
@UnexpectedMaker which board of yours have the issue #186 ?

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker which board of yours have the issue #186 ?

That issue is gone in this commit/PR. I totally forgot to update and close that issue, so I did now. Sorry!

Happy new year! I hope you had a nice break :)

**Review by hathach — APPROVED** [review]
look great, thank you for the pr

**Pull request merged**
