### PR TITLE
Add LOLIN S3

### PR DESCRIPTION
**Pull request by chukwon**
## Description of Change
only add new board - lolin s3

### CODE REVIEW

**Comment by chukwon** [comment]
add lolin_s3 support, also used by espressif_esp32s3_devkitc_1.1 of n16r8

**Comment by lyusupov** [comment]
@chukwon 

```
#define USB_VID           0x239A
#define USB_PID           0x00A5    // TODO temporarily shared with S2 saola wrover
```

VID 0x239A is assigned to Adafruit vendor.

Would you mind to use the VID/PID from Espressif list ? 
https://github.com/espressif/usb-pids/blob/main/allocated-pids.txt#L288
```
0x8118 | Lolin S3 - UF2 Bootloader
```

**Comment by chukwon** [comment]
@lyusupov
don't mind

**Review by hathach — CHANGES_REQUESTED** [review]
please provide all info in the PR template including link to the vid/pid allocation

**Comment by hathach** [comment]
@chukwon there is nothing new in the PR, checkout my above review request.

**Comment by chukwon** [comment]
update completed

**Comment by hathach** [comment]
> update completed

double check the check list, your pr miss ci thing.

**Review by hathach — APPROVED** [review]
look good now, thank you

**Pull request merged**
