### PR TITLE
Feature load2ram

### PR DESCRIPTION
**Pull request by nxf58843**
Work in progress.  Trying to get imxrt1010_evk to target RAM so that it can be loaded with ROM serial downloader.
It builds but does not connect when loaded.

### CODE REVIEW

**Comment by hathach** [comment]
you shouldn't modify the current working flash linker on 1010_evk. Instead you should add an extra board called `imxrt1010_evk_ram` that will allow user to pick either flash/ram at their choice.

**Comment by nxf58843** [comment]
The eventual goal will be to generate a load to RAM image that can be copied from flash by the internal ROM, or loaded through the serial download protocol.  We should be able to support both with the same build.

**Comment by hathach** [comment]
> The eventual goal will be to generate a load to RAM image that can be copied from flash by the internal ROM, or loaded through the serial download protocol. We should be able to support both with the same build.

ah thanks, to be honest, I am a bit clueless on this load2ram :D . Hopefully others who have done something similar could join in and help

**Comment by nxf58843** [comment]
Made progress in another branch.  closing this request.

**Comment by hathach** [comment]
No problems at all, feel free to make the new pr whenever you think it is ready

**Pull request closed without merging**
