### PR TITLE
Adding MCB to Boards

### PR DESCRIPTION
**Pull request by Targett363**
I've had trouble testing (getting Make and IDF to work) but think this should pass.

### CODE REVIEW

**Review by hathach — APPROVED** [review]
look good to me, thank you for your PR.

**Comment by Targett363** [comment]
Just need to beat my system into submission now so I can build my binaries for upload!
Thanks for doing all the UF2 hard work everyone else!

**Comment by hathach** [comment]
@Targett363 IDF change very often (file moving around) most of the time bootloader doesn't need those at all. You will need to export the idf version included as submodule. I will update the doc for that later on.

Also ci does upload binaries as well, you could download it if you want. https://github.com/adafruit/tinyuf2/actions/runs/408837032

**Comment by Targett363** [comment]
Oh you absolute legend! Hadn’t found them!

**Pull request merged**
